---
- name: test
  hosts: all
  become: yes
  tasks:
  - yum:
      name: httpd
      state: present
  - systemd:
      name: httpd
      state: started
      enabled: yes
  - copy:
      dest: /var/www/html/index.html
      content: This is a Nautilus sample file, created using Ansible!
      owner: apache
      group: apache
      mode: '0644'
  - lineinfile:
      path: /var/www/html/index.html
      line: Welcome to xFusionCorp Industries!
      insertbefore: BOF
